"""Open-set fallback, step 1: do max-logit or energy scores reject other plants better?

Pre-registered (addendum) in docs/reports/species-open-set-prereg.md. Every
score's threshold is set on validation for the same in-list coverage as the
current rule (p >= 0.65); e is split by observer, the score with the lowest
false-accept rate on half A is chosen, and its rate on half B is the result.

Run from the repo root:
  PYTHONPATH=src python scripts/open_set_fallback.py \
      --records <sundew-open-set>/open-set-records.jsonl --val-logits <run>/val-logits.npz
"""
from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path

import numpy as np

from sundew_segmentation.species_decision import P_ANSWER, TEMPERATURE, softmax_t

ROOT = Path(__file__).resolve().parents[1]
RELEASE = ROOT / "release/species-v1.0.0"
SEED = 20260930
PASS_BAR = 0.20


def scores(logits: np.ndarray) -> dict[str, np.ndarray]:
    z = logits.astype(np.float64) / TEMPERATURE
    lse = z.max(1) + np.log(np.exp(z - z.max(1, keepdims=True)).sum(1))
    return {"top-1 probability (current)": softmax_t(logits).max(1),
            "max logit": logits.max(1).astype(np.float64),
            "negative energy": TEMPERATURE * lse}


def open_set_logits(records: list[dict], model: Path, cache: Path) -> np.ndarray:
    ids = np.array([int(r["photo_id"]) for r in records])
    if cache.exists():
        d = np.load(cache)
        if np.array_equal(d["photo_id"], ids):
            return d["logits"]
    import onnxruntime as ort
    spec = importlib.util.spec_from_file_location("oos", ROOT / "scripts/score_out_of_list_photos.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    so = ort.SessionOptions()
    so.intra_op_num_threads = 2
    sess = ort.InferenceSession(str(model), so, providers=["CPUExecutionProvider"])
    out = np.stack([sess.run(None, {"pixels": mod.preprocess(Path(r["local_path"]))})[0][0] for r in records])
    np.savez(cache, photo_id=ids, logits=out)
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--records", type=Path, required=True)
    ap.add_argument("--val-logits", type=Path, required=True)
    ap.add_argument("--model", type=Path, default=RELEASE / "model-int8.onnx")
    ap.add_argument("--out", type=Path, default=ROOT / "docs/reports/species-open-set-fallback")
    args = ap.parse_args()

    records = [json.loads(l) for l in open(args.records, encoding="utf-8") if l.strip()]
    logits = open_set_logits(records, args.model, args.records.with_name("open-set-logits.npz"))
    val = np.load(args.val_logits)["scores_onnx_int8"]
    source = np.array([r["source"] for r in records])
    observer = np.array([r["observer_login"] for r in records])

    val_s, os_s = scores(val), scores(logits)
    coverage = float((val_s["top-1 probability (current)"] >= P_ANSWER).mean())
    k = int(round(coverage * len(val)))
    thr = {n: float(np.sort(v)[::-1][k - 1]) for n, v in val_s.items()}
    thr["top-1 probability (current)"] = P_ANSWER  # the shipped rule, exactly

    e = np.isin(source, ["e1", "e2"])
    obs = np.unique(observer[e])
    half_a = set(np.random.default_rng(SEED).permutation(obs)[: len(obs) // 2])
    in_a = np.array([o in half_a for o in observer])
    masks = {"e half A": e & in_a, "e half B": e & ~in_a, "e (all)": e,
             "e1": source == "e1", "e2": source == "e2", "d": source == "d"}
    table = {n: {"threshold": thr[n], "val_coverage": float((val_s[n] >= thr[n]).mean()),
                 **{m: float((os_s[n][mk] >= thr[n]).mean()) for m, mk in masks.items()}} for n in os_s}
    current = "top-1 probability (current)"
    best = min(table, key=lambda n: (table[n]["e half A"], n != current))
    improves = best != current and table[best]["e half A"] < table[current]["e half A"]
    passed = improves and table[best]["e half B"] < PASS_BAR
    spec = importlib.util.spec_from_file_location("sos", ROOT / "scripts/score_open_set.py")
    sos = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(sos)
    result = {"cpu": sos.cpu_model(), "coverage_matched": coverage, "seed": SEED, "half_sizes": {m: int(mk.sum()) for m, mk in masks.items()},
              "chosen_on_half_a": best, "improves_on_current": improves, "passed": passed, "scores": table}
    args.out.with_suffix(".json").write_text(json.dumps(result, indent=1) + "\n")

    pct = lambda x: f"{100 * x:.1f}%"
    L = ["# Open-set fallback, step 1: other scores from the same logits", "",
         "Pre-registered as an addendum to [species-open-set-prereg.md](species-open-set-prereg.md) after the primary "
         "test failed ([species-open-set.md](species-open-set.md)) and before this was computed. Generated by "
         "`scripts/open_set_fallback.py`.", "",
         f"Every score's threshold is set on validation for the current rule's in-list coverage ({pct(coverage)}). "
         f"e is split by observer (seed {SEED}): half A {masks['e half A'].sum()} photos, half B "
         f"{masks['e half B'].sum()}.", "",
         f"**Result: {'PASS' if passed else 'FAIL'}.** Chosen on half A: **{best}**"
         + ("" if improves else " (no score beat the current rule on half A, so the rule stays)") + ". "
         f"On half B it names a sundew for {pct(table[best]['e half B'])} of other plants, against "
         f"{pct(table[current]['e half B'])} for the current rule; the bar is below {pct(PASS_BAR)}.", "",
         "| Score | Threshold | Val coverage | e half A | e half B | e (all) | e1 | e2 | d (no bar) |",
         "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"]
    for n, t in table.items():
        L.append(f"| {n}{' **(chosen)**' if n == best else ''} | {t['threshold']:.3f} | {pct(t['val_coverage'])} | "
                 f"{pct(t['e half A'])} | {pct(t['e half B'])} | {pct(t['e (all)'])} | {pct(t['e1'])} | "
                 f"{pct(t['e2'])} | {pct(t['d'])} |")
    args.out.with_suffix(".md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
