"""Tabulate the frozen-backbone screen written by screen_species_backbones.py.

Reads <screen-dir>/<model>/results.json and predictions.npz for every model that
finished, and writes a Markdown table plus a JSON summary. Intervals come from
an observer-grouped bootstrap of the validation split (observers, not images,
are resampled, because images from one observer are not independent), and
differences are paired: both sides are scored on the same resample.

Nothing here is tuned on validation. The only choice made per model was the
logistic-regression L2 strength, and that was picked by cross-validation on
the training split inside the screen itself.
"""
from __future__ import annotations

import argparse
import json
import pathlib

import numpy as np

ANCHOR = "resnet18-in1k"
# Fine-tuned ResNet-18, 5 seeds, best-epoch val balanced accuracy.
# reports/species-110-baseline.md
FINETUNED = {"crop": 0.5460, "full": 0.5246}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--screen-dir", type=pathlib.Path, required=True)
    p.add_argument("--out-md", type=pathlib.Path, required=True)
    p.add_argument("--out-json", type=pathlib.Path, required=True)
    p.add_argument("--reps", type=int, default=2000)
    p.add_argument("--seed", type=int, default=20260923)
    return p.parse_args()


def balanced(y, pred, weight, n):
    """Balanced accuracy where each image carries a bootstrap multiplicity."""
    tot = np.bincount(y, weights=weight, minlength=n)
    ok = np.bincount(y, weights=weight * (pred == y), minlength=n)
    have = tot > 0
    return float(np.mean(ok[have] / tot[have]))


def main() -> int:
    args = parse_args()
    runs = {}
    for d in sorted(p for p in args.screen_dir.iterdir() if (p / "results.json").exists()):
        runs[d.name] = (json.loads((d / "results.json").read_text()), np.load(d / "predictions.npz"))
    if not runs:
        raise SystemExit(f"no finished models under {args.screen_dir}")

    first = next(iter(runs.values()))[1]
    y, observers = first["val_label"], first["val_observer"]
    for name, (_, z) in runs.items():
        assert np.array_equal(z["val_label"], y), f"{name}: validation order differs"
    n = int(y.max()) + 1
    uniq, obs_idx = np.unique(observers, return_inverse=True)
    rng = np.random.default_rng(args.seed)
    # One shared set of resamples, so every interval and difference is paired.
    weights = np.stack([np.bincount(rng.integers(0, len(uniq), len(uniq)), minlength=len(uniq))[obs_idx]
                        for _ in range(args.reps)]).astype(float)

    def boot(pred):
        return np.array([balanced(y, pred, w, n) for w in weights])

    summary, cache = {"models": {}, "validation_images": int(len(y)),
                      "validation_observers": int(len(uniq)), "bootstrap_reps": args.reps}, {}
    for name, (res, z) in runs.items():
        summary["models"][name] = {"checkpoint": res["checkpoint"], "parameters_m": round(res["parameters"] / 1e6),
                                   "arms": {}}
        for arm, a in res["arms"].items():
            summary["models"][name]["arms"][arm] = {}
            for readout in ("linear", "knn", "zeroshot"):
                if readout not in a:
                    continue
                pred = z[f"{arm}/{readout}"].argmax(1)
                b = boot(pred); cache[(name, arm, readout)] = b
                entry = dict(a[readout], ci95=[float(np.percentile(b, 2.5)), float(np.percentile(b, 97.5))])
                if readout == "linear":
                    entry["chosen_lambda"] = a["chosen_lambda"]
                summary["models"][name]["arms"][arm][readout] = entry

    def delta(b1, b0, point):
        d = b1 - b0
        return {"mean": point, "ci95": [float(np.percentile(d, 2.5)), float(np.percentile(d, 97.5))],
                "p_le_0": float(np.mean(d <= 0))}

    lines = [
        "# Frozen-backbone screen: results table",
        "",
        "Generated by `scripts/summarize_backbone_screen.py`; do not edit by hand.",
        "Interpretation lives in `reports/species-backbone-screen.md`.",
        "",
        f"Validation: {len(y)} images, {len(uniq)} observers, 110 species. "
        f"95% intervals: observer-grouped bootstrap, {args.reps} resamples.",
        "All models frozen, read at 224 px. Reference: fine-tuned ResNet-18 "
        f"(5 seeds) = {FINETUNED['crop']:.4f} crop, {FINETUNED['full']:.4f} full.",
        "",
    ]
    for readout, title in (("linear", "Linear probe"), ("knn", "k-NN (k=10, cosine)"), ("zeroshot", "Zero-shot")):
        rows = [(name, s) for name, s in summary["models"].items()
                if any(readout in s["arms"][arm] for arm in s["arms"])]
        if not rows:
            continue
        rows.sort(key=lambda r: -r[1]["arms"].get("crop", {}).get(readout, {}).get("balanced_accuracy", -1))
        lines += [f"## {title}", "",
                  "| Model | Params | Crop bal. acc [95% CI] | vs fine-tuned R18 | Full | Full-square "
                  "| Crop top-5 | Crop section | Crop - full | Crop - full-square |",
                  "| --- | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"]
        for name, s in rows:
            arms = s["arms"]
            c, f, fs = (arms.get(a, {}).get(readout) for a in ("crop", "full", "full-square"))
            fmt = lambda e: f"{e['balanced_accuracy']:.4f}" if e else "-"
            diffs = []
            for other, e in (("full", f), ("full-square", fs)):
                if not (c and e):
                    diffs.append("-"); continue
                d = delta(cache[(name, "crop", readout)], cache[(name, other, readout)],
                          c["balanced_accuracy"] - e["balanced_accuracy"])
                s.setdefault(f"crop_minus_{other}", {})[readout] = d
                diffs.append(f"{d['mean']:+.4f} [{d['ci95'][0]:+.3f}, {d['ci95'][1]:+.3f}]")
            lines.append(
                f"| `{name}` | {s['parameters_m']}M | "
                + (f"{c['balanced_accuracy']:.4f} [{c['ci95'][0]:.3f}, {c['ci95'][1]:.3f}]" if c else "-")
                + (f" | {c['balanced_accuracy'] - FINETUNED['crop']:+.4f}" if c else " | -")
                + f" | {fmt(f)} | {fmt(fs)}"
                + (f" | {c['top5_accuracy']:.4f} | {c['section_balanced_accuracy']:.4f}" if c else " | - | -")
                + f" | {diffs[0]} | {diffs[1]} |")
        lines.append("")

    if ANCHOR in summary["models"]:
        lines += ["## Paired difference from the frozen ResNet-18 anchor (linear probe, crop arm)", "",
                  "| Model | Delta bal. acc | 95% CI | P(delta <= 0) |", "| --- | ---: | --- | ---: |"]
        a0 = summary["models"][ANCHOR]["arms"]["crop"]["linear"]["balanced_accuracy"]
        for name, s in sorted(summary["models"].items(),
                              key=lambda r: -r[1]["arms"]["crop"]["linear"]["balanced_accuracy"]):
            if name == ANCHOR:
                continue
            d = delta(cache[(name, "crop", "linear")], cache[(ANCHOR, "crop", "linear")],
                      s["arms"]["crop"]["linear"]["balanced_accuracy"] - a0)
            s["vs_anchor_linear_crop"] = d
            lines.append(f"| `{name}` | {d['mean']:+.4f} | [{d['ci95'][0]:+.3f}, {d['ci95'][1]:+.3f}] "
                         f"| {d['p_le_0']:.3f} |")
        lines.append("")

    lines += ["## Linear-probe L2 strength chosen by train-only cross-validation", "",
              "An edge value (1e-6 or 1.0) would mean the grid was too narrow for that model.", "",
              "| Model | crop | full | full-square |", "| --- | ---: | ---: | ---: |"]
    for name, s in summary["models"].items():
        lam = [str(s["arms"].get(a, {}).get("linear", {}).get("chosen_lambda", "-")) for a in ("crop", "full", "full-square")]
        lines.append(f"| `{name}` | " + " | ".join(lam) + " |")
    lines.append("")

    args.out_md.parent.mkdir(parents=True, exist_ok=True)
    args.out_md.write_text("\n".join(lines))
    args.out_json.write_text(json.dumps(summary, indent=2) + "\n")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
